version: '2'
services:
  nginx:
    build: './setup/nginx'
    ports:
     - "8080:80"
     - "4443:443"
    depends_on:
     - webserver
    networks:
     - proxy
  webserver:
    build: './src'
    networks:
     - proxy

networks:
  proxy:
