version: '2'
services:
  nginx:
    build: './setup/nginx'
    ports:
     - "8080:80"
     - "4443:443"
    depends_on:
     - webserver
    networks:
     - proxy
    volumes:
     - "/var/www/firmwarestore:/var/www/firmwarestore"
  webserver:
    build: './src'
    networks:
     - proxy
     - db
    depends_on:
     - db
  db:
   image: tutum/mongodb
   networks:
    - db
   environment:
     MONGODB_USER: tako
     MONGODB_DATABASE: tako
     MONGODB_PASS: password

networks:
  proxy:
  db:
